apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
  namespace: default
type: Opaque
data:
  DB_PASSWORD: cG9zdGdyZXMxMjM=====

#   mdthajuddin@REVINDITLT030 MINGW64 ~
# $ echo -n 'admin-paswsword' | base64
# YWRtaW4tcGFzd3N3b3Jk

 

# mdthajuddin@REVINDITLT030 MINGW64 ~
# $ echo -n 'taj@123' | base64
# dGFqQDEyMw==

# mdthajuddin@REVINDITLT030 MINGW64 ~
# $ echo -n 'cG9zdGdyZXMxMjM=' | base64 --decode
# postgres123
# mdthajuddin@REVINDITLT030 MINGW64 ~
# $



=======
>>>>>>> parent of 4aad6ce (Updated flask-secret.yaml)
