apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: default
data:
  DB_HOST: "postgres.database.svc.cluster.local"
  DB_NAME: "postgres"
  DB_USER: "postgres"
  #DB_TYPE: "master"

